"""Add organization and is_admin fields to User model

Revision ID: 2cd499658788
Revises: ef22738c9485
Create Date: 2025-07-18 04:06:13.862977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd499658788'
down_revision = 'ef22738c9485'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor_data', 'is_anomaly',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='Anomaly detection flag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor_data', 'is_anomaly',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='Anomaly detection flag')
    # ### end Alembic commands ###