"""Add alert_type to alerts

Revision ID: 89c4eb95e29e
Revises: b1d1ccd1ca9e
Create Date: 2025-07-18 08:33:38.787275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c4eb95e29e'
down_revision = 'b1d1ccd1ca9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('alert_type', sa.Enum('HIGH_TEMPERATURE', 'LOW_TEMPERATURE', 'TEMPERATURE_FLUCTUATION', 'HIGH_PH', 'LOW_PH', 'PH_FLUCTUATION', 'LOW_OXYGEN', 'HIGH_OXYGEN', 'OXYGEN_FLUCTUATION', 'HIGH_AMMONIA', 'HIGH_NITRATE', 'HIGH_NITRITE', 'HIGH_TURBIDITY', 'LOW_WATER_LEVEL', 'HIGH_WATER_LEVEL', 'PUMP_FAILURE', 'FILTER_MAINTENANCE', 'SENSOR_MALFUNCTION', 'FISH_MORTALITY', 'FISH_BEHAVIOR_CHANGE', 'DATA_QUALITY_LOW', 'SENSOR_OFFLINE', 'SYSTEM_ERROR', 'MAINTENANCE_REQUIRED', 'ANOMALY_DETECTED', 'PATTERN_CHANGE', 'UNUSUAL_TREND', name='alerttype'), nullable=False))
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_column('alerts', 'alert_type')
    # ### end Alembic commands ###