"""Add organization and is_admin fields to User model

Revision ID: b1d1ccd1ca9e
Revises: 2cd499658788
Create Date: 2025-07-18 08:16:19.887232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d1ccd1ca9e'
down_revision = '2cd499658788'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###