"""Add organization and is_admin fields to User model

Revision ID: ef22738c9485
Revises: 75cb59793d24
Create Date: 2025-07-18 04:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ef22738c9485'
down_revision = '75cb59793d24'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - start ###
    
    # Fix the is_anomaly column type conversion with proper USING clause
    op.execute("""
        ALTER TABLE sensor_data 
        ALTER COLUMN is_anomaly TYPE BOOLEAN 
        USING CASE 
            WHEN is_anomaly = 0 THEN FALSE 
            WHEN is_anomaly = 1 THEN TRUE 
            ELSE FALSE 
        END
    """)
    
    # Add other User model changes here if any
    # op.add_column('users', sa.Column('organization', sa.String(length=255), nullable=True))
    # op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    
    # ### commands auto generated by Alembic - end ###

def downgrade():
    # ### commands auto generated by Alembic - start ###
    
    # Revert is_anomaly back to INTEGER
    op.execute("""
        ALTER TABLE sensor_data 
        ALTER COLUMN is_anomaly TYPE INTEGER 
        USING CASE 
            WHEN is_anomaly = TRUE THEN 1 
            WHEN is_anomaly = FALSE THEN 0 
            ELSE 0 
        END
    """)
    
    # Remove other User model changes if any
    # op.drop_column('users', 'is_admin')
    # op.drop_column('users', 'organization')
    
    # ### commands auto generated by Alembic - end ###